### ISSUE TITLE
some install/running issues

### ISSUE THREAD

**Issue by japhir** [xenodium/chatgpt-shell#72] opened 2023-04-29 09:24 UTC
Trying to install it to give it a whirl, I ran into some issues!

First, installing it directly through use-package gave me an error that I cannot find back in my messages. Maybe it was this one? `reference to free variable ‘chatgpt-shell’`

Then I did M-x list-packages, M-x package-refresh-contents, found the package and used this menu to install it.

I've copied over your use-package config and evaluated it.

I've saved my ~/.authinfo after appending machine api.openai.com password "my-key"

I've added 
```
  (setq chatgpt-shell-openai-key
	(auth-source-pick-first-password :host "api.openai.com"))
```
to the `:config` part (or to the `:init` part) of my use-package call and evaluated it.

In my *Messages* I see this now:
```
assignment to free variable ‘chatgpt-shell-openai-key’
the function ‘auth-source-pick-first-password’ is not known to be defined. 
```

M-x chatgpt-shell doesn't work, returning a weird error that I cannot even copy over here because of encoding issues. I've uploaded the plaintext file here:
[chatgpt-shell.txt](https://github.com/xenodium/chatgpt-shell/files/11358774/chatgpt-shell.txt)

Looks like it's something with the authentication going wrong! I hope this is enough to help debug it :)

**Comment by japhir** [comment] 2023-04-29 09:27
By the way, I've revoked the key in case the weird bytes are secretly giving away my OpenAI key ;-)

**Comment by xenodium** [comment] 2023-04-29 09:56
Thanks for reporting.

> First, installing it directly through use-package gave me an error that I cannot find back in my messages. Maybe it was this one? reference to free variable ‘chatgpt-shell’

I'd need to see the entire `use-package` snippet to help troubleshoot.

>  and used this menu to install it.

Installing via package menu should not be needed with use-package `:ensure t`.

The following snippet just worked for me to install from MELPA:

```emacs-lisp
(use-package chatgpt-shell
  :ensure t
  :custom
  (chatgpt-shell-openai-key
   (lambda ()
     (auth-source-pass-get 'secret "openai-key"))))
```

> Looks like it's something with the authentication going wrong! I hope this is enough to help debug it :)

Lemme try to replicate, but I'll need reproducible steps. Maybe start over...

1. `M-x package-delete chatgpt-shell`
2. Restart Emacs
3. Use the use-package snippet (installing and setting the key).
4. `M-x chatgpt-shell`
5. `ChatGPT> hello`

```
Hello! How can I assist you today?
```

If the above doesn't work, share the entire use-package snippet and any errors you see.

**Comment by xenodium** [comment] 2023-04-29 09:57
ps. What Emacs version are you on?

**Comment by japhir** [comment] 2023-04-29 18:51
I had the same use-package snippet as you, took it from the README. I'm on emacs 28 something. I can try to rerun tonight.

**Comment by japhir** [comment] 2023-04-30 20:32
Here's the error I get after removing the package and then running the use-package snippet:

```
Debugger entered--Lisp error: (file-error "http://melpa.org/packages/chatgpt-shell-20230428.7..." "Not found")
  signal(file-error ("http://melpa.org/packages/chatgpt-shell-20230428.7..." "Not found"))
  package--with-response-buffer-1("http://melpa.org/packages/" #f(compiled-function () #<bytecode -0x108f104fb385072b>) :file "chatgpt-shell-20230428.750.el" :async nil :error-function #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_73> :noerror nil)
  package-install-from-archive(#s(package-desc :name chatgpt-shell :version (20230428 750) :summary "Interaction mode for ChatGPT" :reqs ((emacs (27 1)) (shell-maker (0 17 1))) :kind single :archive "melpa" :dir nil :extras ((:commit . "dbc99097fb14d36466ea78e143ca8b233a0dac86") (:authors ("Alvaro Ramirez https://xenodium.com")) (:maintainers ("Alvaro Ramirez https://xenodium.com")) (:maintainer "Alvaro Ramirez https://xenodium.com") (:url . "https://github.com/xenodium/chatgpt-shell")) :signed nil))
  package-download-transaction((#s(package-desc :name chatgpt-shell :version (20230428 750) :summary "Interaction mode for ChatGPT" :reqs ((emacs (27 1)) (shell-maker (0 17 1))) :kind single :archive "melpa" :dir nil :extras ((:commit . "dbc99097fb14d36466ea78e143ca8b233a0dac86") (:authors ("Alvaro Ramirez https://xenodium.com")) (:maintainers ("Alvaro Ramirez https://xenodium.com")) (:maintainer "Alvaro Ramirez https://xenodium.com") (:url . "https://github.com/xenodium/chatgpt-shell")) :signed nil)))
  package-install(chatgpt-shell)
  use-package-ensure-elpa(chatgpt-shell (t) nil)
  (progn (use-package-ensure-elpa 'chatgpt-shell '(t) 'nil) (defvar use-package--warning98 #'(lambda (keyword err) (let ((msg (format "%s/%s: %s" ... keyword ...))) (display-warning 'use-package msg :error)))) (condition-case err (progn (let ((custom--inhibit-theme-enable nil)) (if (memq 'use-package custom-known-themes) nil (custom-declare-theme 'use-package 'use-package-theme nil) (enable-theme 'use-package) (setq custom-enabled-themes (remq 'use-package custom-enabled-themes))) (custom-theme-set-variables 'use-package '(chatgpt-shell-openai-key (lambda nil ...) nil nil "Customized with use-package chatgpt-shell"))) (let ((now (current-time))) (message "%s..." "Loading package chatgpt-shell") (prog1 (if (not (require ... nil t)) (display-warning 'use-package (format "Cannot load %s" ...) :error)) (let ((elapsed ...)) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package chatgpt-shell" elapsed) (message "%s...done" "Loading package chatgpt-shell")))))) ((debug error) (funcall use-package--warning98 :catch err))))
  (progn (progn (use-package-ensure-elpa 'chatgpt-shell '(t) 'nil) (defvar use-package--warning98 #'(lambda (keyword err) (let ((msg ...)) (display-warning 'use-package msg :error)))) (condition-case err (progn (let ((custom--inhibit-theme-enable nil)) (if (memq 'use-package custom-known-themes) nil (custom-declare-theme 'use-package 'use-package-theme nil) (enable-theme 'use-package) (setq custom-enabled-themes (remq ... custom-enabled-themes))) (custom-theme-set-variables 'use-package '(chatgpt-shell-openai-key ... nil nil "Customized with use-package chatgpt-shell"))) (let ((now (current-time))) (message "%s..." "Loading package chatgpt-shell") (prog1 (if (not ...) (display-warning ... ... :error)) (let (...) (if ... ... ...))))) ((debug error) (funcall use-package--warning98 :catch err)))))
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  command-execute(eval-last-sexp)
```

**Comment by xenodium** [comment] 2023-04-30 21:20
Something's up with local package registry. Could you try refreshing packages and install again?

**Comment by japhir** [comment] 2023-05-01 03:46
Is that the same as M-x package-refresh-contents, which I had done for my first try already? Or the thing that happens when you press U after list-packages (which I've also done). I can try it in a clean environment in a bit.

**Comment by japhir** [comment] 2023-05-01 03:51
When I run it with [with-emacs](https://github.com/alphapapa/with-emacs.sh) use-package and then run your use-package snippet from scratch, I only get some warnings:
```
Warning (comp): chatgpt-shell.el:1176:31: Warning: reference to free variable ‘org-babel-default-header-args’ Disable showing Disable logging
Warning (comp): chatgpt-shell.el:1183:48: Warning: reference to free variable ‘org-babel-error-buffer-name’ Disable showing Disable logging
Warning (comp): chatgpt-shell.el:1175:31: Warning: the function ‘org-babel-merge-params’ is not known to be defined. Disable showing Disable logging
Warning (comp): chatgpt-shell.el:1172:29: Warning: the function ‘org-babel-process-params’ is not known to be defined. Disable showing Disable logging
```
so there must be something going on in [my configuration](https://github.com/japhir/ArchConfigs/blob/master/myinit.org) or with the interaction with something there… hmmm

**Comment by japhir** [comment] 2023-05-01 04:02
Ok I've now followed all steps to start from scratch, and this time it launched it's separate buffer! Then it told me I had provided an incorrect API key, which I fixed by calling the second example of authentication in your README (getting it to look in ~/.authinfo). Now I've run into an upstream issue: `You exceeded your current quota, please check your plan and billing details.curl: (22) The requested URL returned error: 429` ;-).

Thanks for the help, I think that fixes my issues and perhaps gives you some pointers for getting it to run cleanly in a fresh install. Cheers!

PS: I'm on: GNU Emacs 29.0.50 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.24.32, cairo version 1.17.4) of 2022-03-05

**Comment by xenodium** [comment] 2023-05-01 07:05
Ah good to hear. Looks like the installation and setup are good now. Error is coming straight from the OpenAI API. It's an account/billing issue with OpenAI from here on, similar to https://github.com/xenodium/chatgpt-shell/issues/69#issuecomment-1525335720 Closing issue.

**Closed** 2023-05-01 07:05 UTC
