### ISSUE TITLE
option --no-progress-meter: is unknown

### ISSUE THREAD

**Issue by jacquesdurden** [xenodium/chatgpt-shell#1] opened 2023-03-22 09:58 UTC
Hi, thank you for this great contribution. I tried it and configured the key. However, one option used by curl (on Mac) seems unknown: "--no-progress-meter: is unknown". I've thus installed the newer version of brew, and replaced the call to "curl" in chatgpt-shell.el by "/usr/local/bin/curl" that points to it, but now I got another error : "curl: (22) The requested URL returned error: 429" Any idea of how to solve it? Thanks.

**Comment by jacquesdurden** [comment] 2023-03-22 21:05
Weird, I still have the same error 429 issue while I can access chatgpt from the web without any trouble.

**Comment by xenodium** [comment] 2023-03-22 21:45
Try running this from command line (with YOUR_KEY) and see if you can reproduce still:

    curl https://api.openai.com/v1/chat/completions --fail --no-progress-meter -m 30 -H Content-Type: application/json -H Authorization: Bearer YOUR_KEY -d {"model":"gpt-3.5-turbo","messages":[{"role":"user","content":"hi"}]}

**Comment by xenodium** [comment] 2023-03-24 09:06
The latest checks for curl version 7.67 or newer. Looks like 429 error is unrelated. Will close this issue, but please ping if you still having trouble.

**Closed by xenodium** 2023-03-24 09:06 UTC
